// Copyright 2025 Fabien Dupont
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: infractl/provider/v1/provider.proto

package providerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{0}
}

type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`
	Dependencies  []string               `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ProviderInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ProviderInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiPrefix     string                 `protobuf:"bytes,1,opt,name=api_prefix,json=apiPrefix,proto3" json:"api_prefix,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetApiPrefix() string {
	if x != nil {
		return x.ApiPrefix
	}
	return ""
}

func (x *InitRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{3}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{4}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{5}
}

type GetRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesRequest) Reset() {
	*x = GetRoutesRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesRequest) ProtoMessage() {}

func (x *GetRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesRequest.ProtoReflect.Descriptor instead.
func (*GetRoutesRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{6}
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{7}
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoutesResponse) Reset() {
	*x = GetRoutesResponse{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoutesResponse) ProtoMessage() {}

func (x *GetRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoutesResponse.ProtoReflect.Descriptor instead.
func (*GetRoutesResponse) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *GetRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type HTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequest) Reset() {
	*x = HTTPRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequest) ProtoMessage() {}

func (x *HTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequest.ProtoReflect.Descriptor instead.
func (*HTTPRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{9}
}

func (x *HTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type HTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponse) Reset() {
	*x = HTTPResponse{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponse) ProtoMessage() {}

func (x *HTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponse.ProtoReflect.Descriptor instead.
func (*HTTPResponse) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *HTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetHookRegistrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHookRegistrationsRequest) Reset() {
	*x = GetHookRegistrationsRequest{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHookRegistrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHookRegistrationsRequest) ProtoMessage() {}

func (x *GetHookRegistrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHookRegistrationsRequest.ProtoReflect.Descriptor instead.
func (*GetHookRegistrationsRequest) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{11}
}

type HookRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Sync          bool                   `protobuf:"varint,3,opt,name=sync,proto3" json:"sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRegistration) Reset() {
	*x = HookRegistration{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRegistration) ProtoMessage() {}

func (x *HookRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRegistration.ProtoReflect.Descriptor instead.
func (*HookRegistration) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{12}
}

func (x *HookRegistration) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *HookRegistration) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HookRegistration) GetSync() bool {
	if x != nil {
		return x.Sync
	}
	return false
}

type HookRegistrationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registrations []*HookRegistration    `protobuf:"bytes,1,rep,name=registrations,proto3" json:"registrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRegistrationList) Reset() {
	*x = HookRegistrationList{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRegistrationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRegistrationList) ProtoMessage() {}

func (x *HookRegistrationList) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRegistrationList.ProtoReflect.Descriptor instead.
func (*HookRegistrationList) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *HookRegistrationList) GetRegistrations() []*HookRegistration {
	if x != nil {
		return x.Registrations
	}
	return nil
}

type HookEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Feature       string                 `protobuf:"bytes,1,opt,name=feature,proto3" json:"feature,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookEvent) Reset() {
	*x = HookEvent{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookEvent) ProtoMessage() {}

func (x *HookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookEvent.ProtoReflect.Descriptor instead.
func (*HookEvent) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{14}
}

func (x *HookEvent) GetFeature() string {
	if x != nil {
		return x.Feature
	}
	return ""
}

func (x *HookEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *HookEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HookResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_provider_v1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_infractl_provider_v1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *HookResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HookResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_infractl_provider_v1_provider_proto protoreflect.FileDescriptor

const file_infractl_provider_v1_provider_proto_rawDesc = "" +
	"\n" +
	"#infractl/provider/v1/provider.proto\x12\x14infractl.provider.v1\"\x10\n" +
	"\x0eGetInfoRequest\"|\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\"\xae\x01\n" +
	"\vInitRequest\x12\x1d\n" +
	"\n" +
	"api_prefix\x18\x01 \x01(\tR\tapiPrefix\x12E\n" +
	"\x06config\x18\x02 \x03(\v2-.infractl.provider.v1.InitRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x0e\n" +
	"\fInitResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x12\n" +
	"\x10GetRoutesRequest\"3\n" +
	"\x05Route\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"H\n" +
	"\x11GetRoutesResponse\x123\n" +
	"\x06routes\x18\x01 \x03(\v2\x1b.infractl.provider.v1.RouteR\x06routes\"\xe9\x01\n" +
	"\vHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12H\n" +
	"\aheaders\x18\x03 \x03(\v2..infractl.provider.v1.HTTPRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\fHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12I\n" +
	"\aheaders\x18\x02 \x03(\v2/.infractl.provider.v1.HTTPResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1d\n" +
	"\x1bGetHookRegistrationsRequest\"V\n" +
	"\x10HookRegistration\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x12\n" +
	"\x04sync\x18\x03 \x01(\bR\x04sync\"d\n" +
	"\x14HookRegistrationList\x12L\n" +
	"\rregistrations\x18\x01 \x03(\v2&.infractl.provider.v1.HookRegistrationR\rregistrations\"U\n" +
	"\tHookEvent\x12\x18\n" +
	"\afeature\x18\x01 \x01(\tR\afeature\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"<\n" +
	"\n" +
	"HookResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x90\x05\n" +
	"\x10ExternalProvider\x12S\n" +
	"\aGetInfo\x12$.infractl.provider.v1.GetInfoRequest\x1a\".infractl.provider.v1.ProviderInfo\x12M\n" +
	"\x04Init\x12!.infractl.provider.v1.InitRequest\x1a\".infractl.provider.v1.InitResponse\x12Y\n" +
	"\bShutdown\x12%.infractl.provider.v1.ShutdownRequest\x1a&.infractl.provider.v1.ShutdownResponse\x12\\\n" +
	"\tGetRoutes\x12&.infractl.provider.v1.GetRoutesRequest\x1a'.infractl.provider.v1.GetRoutesResponse\x12S\n" +
	"\n" +
	"HandleHTTP\x12!.infractl.provider.v1.HTTPRequest\x1a\".infractl.provider.v1.HTTPResponse\x12u\n" +
	"\x14GetHookRegistrations\x121.infractl.provider.v1.GetHookRegistrationsRequest\x1a*.infractl.provider.v1.HookRegistrationList\x12S\n" +
	"\x0eHandleSyncHook\x12\x1f.infractl.provider.v1.HookEvent\x1a .infractl.provider.v1.HookResultBQZOgithub.com/fabiendupont/infractl/provider/proto/infractl/provider/v1;providerv1b\x06proto3"

var (
	file_infractl_provider_v1_provider_proto_rawDescOnce sync.Once
	file_infractl_provider_v1_provider_proto_rawDescData []byte
)

func file_infractl_provider_v1_provider_proto_rawDescGZIP() []byte {
	file_infractl_provider_v1_provider_proto_rawDescOnce.Do(func() {
		file_infractl_provider_v1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infractl_provider_v1_provider_proto_rawDesc), len(file_infractl_provider_v1_provider_proto_rawDesc)))
	})
	return file_infractl_provider_v1_provider_proto_rawDescData
}

var file_infractl_provider_v1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_infractl_provider_v1_provider_proto_goTypes = []any{
	(*GetInfoRequest)(nil),              // 0: infractl.provider.v1.GetInfoRequest
	(*ProviderInfo)(nil),                // 1: infractl.provider.v1.ProviderInfo
	(*InitRequest)(nil),                 // 2: infractl.provider.v1.InitRequest
	(*InitResponse)(nil),                // 3: infractl.provider.v1.InitResponse
	(*ShutdownRequest)(nil),             // 4: infractl.provider.v1.ShutdownRequest
	(*ShutdownResponse)(nil),            // 5: infractl.provider.v1.ShutdownResponse
	(*GetRoutesRequest)(nil),            // 6: infractl.provider.v1.GetRoutesRequest
	(*Route)(nil),                       // 7: infractl.provider.v1.Route
	(*GetRoutesResponse)(nil),           // 8: infractl.provider.v1.GetRoutesResponse
	(*HTTPRequest)(nil),                 // 9: infractl.provider.v1.HTTPRequest
	(*HTTPResponse)(nil),                // 10: infractl.provider.v1.HTTPResponse
	(*GetHookRegistrationsRequest)(nil), // 11: infractl.provider.v1.GetHookRegistrationsRequest
	(*HookRegistration)(nil),            // 12: infractl.provider.v1.HookRegistration
	(*HookRegistrationList)(nil),        // 13: infractl.provider.v1.HookRegistrationList
	(*HookEvent)(nil),                   // 14: infractl.provider.v1.HookEvent
	(*HookResult)(nil),                  // 15: infractl.provider.v1.HookResult
	nil,                                 // 16: infractl.provider.v1.InitRequest.ConfigEntry
	nil,                                 // 17: infractl.provider.v1.HTTPRequest.HeadersEntry
	nil,                                 // 18: infractl.provider.v1.HTTPResponse.HeadersEntry
}
var file_infractl_provider_v1_provider_proto_depIdxs = []int32{
	16, // 0: infractl.provider.v1.InitRequest.config:type_name -> infractl.provider.v1.InitRequest.ConfigEntry
	7,  // 1: infractl.provider.v1.GetRoutesResponse.routes:type_name -> infractl.provider.v1.Route
	17, // 2: infractl.provider.v1.HTTPRequest.headers:type_name -> infractl.provider.v1.HTTPRequest.HeadersEntry
	18, // 3: infractl.provider.v1.HTTPResponse.headers:type_name -> infractl.provider.v1.HTTPResponse.HeadersEntry
	12, // 4: infractl.provider.v1.HookRegistrationList.registrations:type_name -> infractl.provider.v1.HookRegistration
	0,  // 5: infractl.provider.v1.ExternalProvider.GetInfo:input_type -> infractl.provider.v1.GetInfoRequest
	2,  // 6: infractl.provider.v1.ExternalProvider.Init:input_type -> infractl.provider.v1.InitRequest
	4,  // 7: infractl.provider.v1.ExternalProvider.Shutdown:input_type -> infractl.provider.v1.ShutdownRequest
	6,  // 8: infractl.provider.v1.ExternalProvider.GetRoutes:input_type -> infractl.provider.v1.GetRoutesRequest
	9,  // 9: infractl.provider.v1.ExternalProvider.HandleHTTP:input_type -> infractl.provider.v1.HTTPRequest
	11, // 10: infractl.provider.v1.ExternalProvider.GetHookRegistrations:input_type -> infractl.provider.v1.GetHookRegistrationsRequest
	14, // 11: infractl.provider.v1.ExternalProvider.HandleSyncHook:input_type -> infractl.provider.v1.HookEvent
	1,  // 12: infractl.provider.v1.ExternalProvider.GetInfo:output_type -> infractl.provider.v1.ProviderInfo
	3,  // 13: infractl.provider.v1.ExternalProvider.Init:output_type -> infractl.provider.v1.InitResponse
	5,  // 14: infractl.provider.v1.ExternalProvider.Shutdown:output_type -> infractl.provider.v1.ShutdownResponse
	8,  // 15: infractl.provider.v1.ExternalProvider.GetRoutes:output_type -> infractl.provider.v1.GetRoutesResponse
	10, // 16: infractl.provider.v1.ExternalProvider.HandleHTTP:output_type -> infractl.provider.v1.HTTPResponse
	13, // 17: infractl.provider.v1.ExternalProvider.GetHookRegistrations:output_type -> infractl.provider.v1.HookRegistrationList
	15, // 18: infractl.provider.v1.ExternalProvider.HandleSyncHook:output_type -> infractl.provider.v1.HookResult
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_infractl_provider_v1_provider_proto_init() }
func file_infractl_provider_v1_provider_proto_init() {
	if File_infractl_provider_v1_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infractl_provider_v1_provider_proto_rawDesc), len(file_infractl_provider_v1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infractl_provider_v1_provider_proto_goTypes,
		DependencyIndexes: file_infractl_provider_v1_provider_proto_depIdxs,
		MessageInfos:      file_infractl_provider_v1_provider_proto_msgTypes,
	}.Build()
	File_infractl_provider_v1_provider_proto = out.File
	file_infractl_provider_v1_provider_proto_goTypes = nil
	file_infractl_provider_v1_provider_proto_depIdxs = nil
}
