// Copyright 2025 Fabien Dupont
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: infractl/provider/v1/provider.proto

package providerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExternalProvider_GetInfo_FullMethodName              = "/infractl.provider.v1.ExternalProvider/GetInfo"
	ExternalProvider_Init_FullMethodName                 = "/infractl.provider.v1.ExternalProvider/Init"
	ExternalProvider_Shutdown_FullMethodName             = "/infractl.provider.v1.ExternalProvider/Shutdown"
	ExternalProvider_GetRoutes_FullMethodName            = "/infractl.provider.v1.ExternalProvider/GetRoutes"
	ExternalProvider_HandleHTTP_FullMethodName           = "/infractl.provider.v1.ExternalProvider/HandleHTTP"
	ExternalProvider_GetHookRegistrations_FullMethodName = "/infractl.provider.v1.ExternalProvider/GetHookRegistrations"
	ExternalProvider_HandleSyncHook_FullMethodName       = "/infractl.provider.v1.ExternalProvider/HandleSyncHook"
)

// ExternalProviderClient is the client API for ExternalProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalProviderClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error)
	GetHookRegistrations(ctx context.Context, in *GetHookRegistrationsRequest, opts ...grpc.CallOption) (*HookRegistrationList, error)
	HandleSyncHook(ctx context.Context, in *HookEvent, opts ...grpc.CallOption) (*HookResult, error)
}

type externalProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalProviderClient(cc grpc.ClientConnInterface) ExternalProviderClient {
	return &externalProviderClient{cc}
}

func (c *externalProviderClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, ExternalProvider_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, ExternalProvider_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ExternalProvider_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, ExternalProvider_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) HandleHTTP(ctx context.Context, in *HTTPRequest, opts ...grpc.CallOption) (*HTTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HTTPResponse)
	err := c.cc.Invoke(ctx, ExternalProvider_HandleHTTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) GetHookRegistrations(ctx context.Context, in *GetHookRegistrationsRequest, opts ...grpc.CallOption) (*HookRegistrationList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookRegistrationList)
	err := c.cc.Invoke(ctx, ExternalProvider_GetHookRegistrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *externalProviderClient) HandleSyncHook(ctx context.Context, in *HookEvent, opts ...grpc.CallOption) (*HookResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResult)
	err := c.cc.Invoke(ctx, ExternalProvider_HandleSyncHook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalProviderServer is the server API for ExternalProvider service.
// All implementations must embed UnimplementedExternalProviderServer
// for forward compatibility.
type ExternalProviderServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error)
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error)
	GetHookRegistrations(context.Context, *GetHookRegistrationsRequest) (*HookRegistrationList, error)
	HandleSyncHook(context.Context, *HookEvent) (*HookResult, error)
	mustEmbedUnimplementedExternalProviderServer()
}

// UnimplementedExternalProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExternalProviderServer struct{}

func (UnimplementedExternalProviderServer) GetInfo(context.Context, *GetInfoRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedExternalProviderServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedExternalProviderServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedExternalProviderServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedExternalProviderServer) HandleHTTP(context.Context, *HTTPRequest) (*HTTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleHTTP not implemented")
}
func (UnimplementedExternalProviderServer) GetHookRegistrations(context.Context, *GetHookRegistrationsRequest) (*HookRegistrationList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHookRegistrations not implemented")
}
func (UnimplementedExternalProviderServer) HandleSyncHook(context.Context, *HookEvent) (*HookResult, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleSyncHook not implemented")
}
func (UnimplementedExternalProviderServer) mustEmbedUnimplementedExternalProviderServer() {}
func (UnimplementedExternalProviderServer) testEmbeddedByValue()                          {}

// UnsafeExternalProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalProviderServer will
// result in compilation errors.
type UnsafeExternalProviderServer interface {
	mustEmbedUnimplementedExternalProviderServer()
}

func RegisterExternalProviderServer(s grpc.ServiceRegistrar, srv ExternalProviderServer) {
	// If the following call panics, it indicates UnimplementedExternalProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExternalProvider_ServiceDesc, srv)
}

func _ExternalProvider_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_HandleHTTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).HandleHTTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_HandleHTTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).HandleHTTP(ctx, req.(*HTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_GetHookRegistrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHookRegistrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).GetHookRegistrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_GetHookRegistrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).GetHookRegistrations(ctx, req.(*GetHookRegistrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExternalProvider_HandleSyncHook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalProviderServer).HandleSyncHook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExternalProvider_HandleSyncHook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalProviderServer).HandleSyncHook(ctx, req.(*HookEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalProvider_ServiceDesc is the grpc.ServiceDesc for ExternalProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infractl.provider.v1.ExternalProvider",
	HandlerType: (*ExternalProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ExternalProvider_GetInfo_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _ExternalProvider_Init_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ExternalProvider_Shutdown_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _ExternalProvider_GetRoutes_Handler,
		},
		{
			MethodName: "HandleHTTP",
			Handler:    _ExternalProvider_HandleHTTP_Handler,
		},
		{
			MethodName: "GetHookRegistrations",
			Handler:    _ExternalProvider_GetHookRegistrations_Handler,
		},
		{
			MethodName: "HandleSyncHook",
			Handler:    _ExternalProvider_HandleSyncHook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infractl/provider/v1/provider.proto",
}
