// Copyright 2025 The infractl Authors
// SPDX-License-Identifier: Apache-2.0

package grpc

import (
	"context"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// GatewayConfig holds the configuration for the grpc-gateway REST proxy.
type GatewayConfig struct {
	GRPCAddr string
	HTTPAddr string
}

// Gateway is a grpc-gateway REST proxy that translates HTTP/JSON requests
// to gRPC calls. Providers register their gateway handlers via RegisterFunc.
type Gateway struct {
	Mux    *runtime.ServeMux
	Config GatewayConfig
	Logger zerolog.Logger
	conn   *grpc.ClientConn
}

// RegisterFunc is the signature of grpc-gateway registration functions
// generated by protoc-gen-grpc-gateway.
type RegisterFunc func(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error

// NewGateway creates a grpc-gateway proxy that connects to the given gRPC
// server address.
func NewGateway(cfg GatewayConfig, logger zerolog.Logger) (*Gateway, error) {
	grpcAddr := cfg.GRPCAddr
	if grpcAddr == "" {
		grpcAddr = "localhost:9090"
	}

	conn, err := grpc.NewClient(grpcAddr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		return nil, err
	}

	return &Gateway{
		Mux:    runtime.NewServeMux(),
		Config: cfg,
		Logger: logger,
		conn:   conn,
	}, nil
}

// RegisterService registers a grpc-gateway handler for a gRPC service.
func (g *Gateway) RegisterService(ctx context.Context, fn RegisterFunc) error {
	return fn(ctx, g.Mux, g.conn)
}

// ListenAndServe starts the HTTP proxy server.
func (g *Gateway) ListenAndServe() error {
	addr := g.Config.HTTPAddr
	if addr == "" {
		addr = ":8081"
	}

	g.Logger.Info().Str("addr", addr).Msg("starting gRPC-gateway HTTP proxy")
	return http.ListenAndServe(addr, g.Mux)
}

// Handler returns the gateway mux as an http.Handler, allowing it to be
// mounted on an existing chi router or http.ServeMux.
func (g *Gateway) Handler() http.Handler {
	return g.Mux
}

// Close closes the underlying gRPC client connection.
func (g *Gateway) Close() error {
	return g.conn.Close()
}
