// Copyright 2025 The infractl Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: infractl/resource/v1/metadata.proto

package resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metadata is the shared metadata for all infractl resources.
// It matches the fields in resource.Resource.
type Metadata struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrgId             string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels            map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations       map[string]string      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Finalizers        []string               `protobuf:"bytes,5,rep,name=finalizers,proto3" json:"finalizers,omitempty"`
	Generation        int64                  `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	ResourceVersion   int64                  `protobuf:"varint,7,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Owner             string                 `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Creator           string                 `protobuf:"bytes,9,opt,name=creator,proto3" json:"creator,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletionTimestamp *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=deletion_timestamp,json=deletionTimestamp,proto3" json:"deletion_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_infractl_resource_v1_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *Metadata) GetFinalizers() []string {
	if x != nil {
		return x.Finalizers
	}
	return nil
}

func (x *Metadata) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Metadata) GetResourceVersion() int64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *Metadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Metadata) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Metadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Metadata) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Metadata) GetDeletionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletionTimestamp
	}
	return nil
}

// ListRequest is the common request shape for list operations.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Continue      string                 `protobuf:"bytes,3,opt,name=continue,proto3" json:"continue,omitempty"`
	Filter        string                 `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          string                 `protobuf:"bytes,5,opt,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_infractl_resource_v1_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetContinue() string {
	if x != nil {
		return x.Continue
	}
	return ""
}

func (x *ListRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

// ListResponse is the common response wrapper for paginated lists.
type ListResponseMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Continue      string                 `protobuf:"bytes,1,opt,name=continue,proto3" json:"continue,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponseMeta) Reset() {
	*x = ListResponseMeta{}
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponseMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponseMeta) ProtoMessage() {}

func (x *ListResponseMeta) ProtoReflect() protoreflect.Message {
	mi := &file_infractl_resource_v1_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponseMeta.ProtoReflect.Descriptor instead.
func (*ListResponseMeta) Descriptor() ([]byte, []int) {
	return file_infractl_resource_v1_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *ListResponseMeta) GetContinue() string {
	if x != nil {
		return x.Continue
	}
	return ""
}

func (x *ListResponseMeta) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_infractl_resource_v1_metadata_proto protoreflect.FileDescriptor

const file_infractl_resource_v1_metadata_proto_rawDesc = "" +
	"\n" +
	"#infractl/resource/v1/metadata.proto\x12\x14infractl.resource.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x05\n" +
	"\bMetadata\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12B\n" +
	"\x06labels\x18\x03 \x03(\v2*.infractl.resource.v1.Metadata.LabelsEntryR\x06labels\x12Q\n" +
	"\vannotations\x18\x04 \x03(\v2/.infractl.resource.v1.Metadata.AnnotationsEntryR\vannotations\x12\x1e\n" +
	"\n" +
	"finalizers\x18\x05 \x03(\tR\n" +
	"finalizers\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x03R\n" +
	"generation\x12)\n" +
	"\x10resource_version\x18\a \x01(\x03R\x0fresourceVersion\x12\x14\n" +
	"\x05owner\x18\b \x01(\tR\x05owner\x12\x18\n" +
	"\acreator\x18\t \x01(\tR\acreator\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12I\n" +
	"\x12deletion_timestamp\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x11deletionTimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x82\x01\n" +
	"\vListRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bcontinue\x18\x03 \x01(\tR\bcontinue\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\x12\x12\n" +
	"\x04sort\x18\x05 \x01(\tR\x04sort\"D\n" +
	"\x10ListResponseMeta\x12\x1a\n" +
	"\bcontinue\x18\x01 \x01(\tR\bcontinue\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05totalBQZOgithub.com/fabiendupont/infractl/resource/proto/infractl/resource/v1;resourcev1b\x06proto3"

var (
	file_infractl_resource_v1_metadata_proto_rawDescOnce sync.Once
	file_infractl_resource_v1_metadata_proto_rawDescData []byte
)

func file_infractl_resource_v1_metadata_proto_rawDescGZIP() []byte {
	file_infractl_resource_v1_metadata_proto_rawDescOnce.Do(func() {
		file_infractl_resource_v1_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_infractl_resource_v1_metadata_proto_rawDesc), len(file_infractl_resource_v1_metadata_proto_rawDesc)))
	})
	return file_infractl_resource_v1_metadata_proto_rawDescData
}

var file_infractl_resource_v1_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_infractl_resource_v1_metadata_proto_goTypes = []any{
	(*Metadata)(nil),              // 0: infractl.resource.v1.Metadata
	(*ListRequest)(nil),           // 1: infractl.resource.v1.ListRequest
	(*ListResponseMeta)(nil),      // 2: infractl.resource.v1.ListResponseMeta
	nil,                           // 3: infractl.resource.v1.Metadata.LabelsEntry
	nil,                           // 4: infractl.resource.v1.Metadata.AnnotationsEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_infractl_resource_v1_metadata_proto_depIdxs = []int32{
	3, // 0: infractl.resource.v1.Metadata.labels:type_name -> infractl.resource.v1.Metadata.LabelsEntry
	4, // 1: infractl.resource.v1.Metadata.annotations:type_name -> infractl.resource.v1.Metadata.AnnotationsEntry
	5, // 2: infractl.resource.v1.Metadata.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: infractl.resource.v1.Metadata.updated_at:type_name -> google.protobuf.Timestamp
	5, // 4: infractl.resource.v1.Metadata.deletion_timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_infractl_resource_v1_metadata_proto_init() }
func file_infractl_resource_v1_metadata_proto_init() {
	if File_infractl_resource_v1_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_infractl_resource_v1_metadata_proto_rawDesc), len(file_infractl_resource_v1_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infractl_resource_v1_metadata_proto_goTypes,
		DependencyIndexes: file_infractl_resource_v1_metadata_proto_depIdxs,
		MessageInfos:      file_infractl_resource_v1_metadata_proto_msgTypes,
	}.Build()
	File_infractl_resource_v1_metadata_proto = out.File
	file_infractl_resource_v1_metadata_proto_goTypes = nil
	file_infractl_resource_v1_metadata_proto_depIdxs = nil
}
